name: Build, Lint & Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: Build, Lint & Test Linux
        if: runner.os == 'Linux'
        env:
          TEST_BROWSERS: ChromeHeadless,Firefox
        run: xvfb-run npm run all

      - name: Build, Lint & Test others
        if: runner.os != 'Linux'
        env:
          TEST_BROWSERS: ChromeHeadless
        run: npm run all

      - name: Setup and build example starter
        working-directory: ./starter
        run: |
          npm install
          npm run all
