name: Build & Test

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        node-version: [ 16.8 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

#  Check debugger
    - name: Install debugger dependencies
      working-directory: ./debugger
      run: npm install

    - name: Test debugger
      working-directory: ./debugger
      if: matrix.os == 'ubuntu-latest'
      env:
        TEST_BROWSERS: ChromeHeadless
      run: xvfb-run npm run all

    - name: Build debugger
      working-directory: ./debugger
      if: matrix.os != 'ubuntu-latest'
      env:
        TEST_BROWSERS: ChromeHeadless,Firefox
      run: npm run all

    - name: Setup and build debugger starter
      working-directory: ./debugger/starter
      run: |
        npm install
        npm run all

#  Check modeler
    - name: Install modeler dependencies
      working-directory: ./modeler
      run: npm install

    - name: Test modeler
      working-directory: ./modeler
      if: matrix.os == 'ubuntu-latest'
      env:
        TEST_BROWSERS: ChromeHeadless
      run: xvfb-run npm run all

    - name: Build modeler
      working-directory: ./modeler
      if: matrix.os != 'ubuntu-latest'
      env:
        TEST_BROWSERS: ChromeHeadless,Firefox
      run: npm run all

    - name: Setup and build modeler starter
      working-directory: ./modeler/starter
      run: |
        npm install
        npm run all